spring.application.name=training-account-item

# H2データベースへの接続設定
# インメモリモードで「bokidb」という名前のデータベースに接続
spring.datasource.url=jdbc:h2:mem:bokidb
# H2用のJDBCドライバを指定
spring.datasource.driver-class-name=org.h2.Driver
# データベースへの接続時のユーザー名
spring.datasource.username=sa
# データベースへの接続時のパスワード
spring.datasource.password=
# H2コンソールを有効化
spring.h2.console.enabled=true
# H2コンソールのアクセスURL（http://localhost:8080/h2-console）
spring.h2.console.path=/h2-console
#Log表示設定
logging.level.com.example.webapp.repository=debug
#SQLスクリプトの初期化モードを設定
spring.sql.init.mode=always